AWSTemplateFormatVersion: "2010-09-09"

Description: Enable VPC Flow Logs to CloudWatch Logs

Parameters:

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

Resources:

  FlowLogsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/vpc/production-flow-logs
      RetentionInDays: 30

  FlowLogsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: production-vpc-flowlogs-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: FlowLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Resource: "*"

  VPCFlowLogs:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceType: VPC
      ResourceId: !Ref VPCId
      TrafficType: ALL
      LogDestinationType: cloud-watch-logs
      LogGroupName: !Ref FlowLogsLogGroup
      DeliverLogsPermissionArn: !GetAtt FlowLogsRole.Arn

Outputs:

  LogGroup:
    Description: CloudWatch Log Group
    Value: !Ref FlowLogsLogGroup

  FlowLogsRoleArn:
    Description: IAM Role ARN
    Value: !GetAtt FlowLogsRole.Arn